name: Deployment pipeline

env:
  CONDITION: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main'}}

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: npm install
        run: npm install  
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: Install Playwright Browser
        run: |
          sudo npx playwright install-deps
          npx playwright install
      - name: e2e test
        run: npm run test:e2e
      - name: Deploy
        # Run this step only if the branch is main and the event is a push
        if: ${{ env.CONDITION == true }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ env.CONDITION == true && contains(join(toJson(github.event.commits.*.message), '\n'), '#skip') == false }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  notification:
    needs: [tag_release]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Notify Success
        if: ${{ needs.simple_deployment_pipeline.result == 'success' }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          text: "A new version of Pokedex deployed"
          description: to ${{ secrets.RENDER_DEPLOYED_URL }}
      - name: Notify Failure
        if: ${{ needs.simple_deployment_pipeline.result == 'failure' }}
        uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          text: "Build failed"
          description: commit ${{ github.sha }} failed to build

  